require('dotenv').config();
const mongoose = require('mongoose');

// Models
const Category = require('./models/Category');
const Product = require('./models/Product');
const Slider = require('./models/Slider');
const Settings = require('./models/Settings');

// Base URL for local images — served by Express from client/public/images/
const IMG = (filename) => `http://localhost:5000/images/${filename}`;

const categories = [
  { name: 'Biryani', slug: 'biryani', description: 'Aromatic rice dishes', imageUrl: IMG('biryani 1_result.webp'), displayOrder: 1 },
  { name: 'Chicken', slug: 'chicken', description: 'Delicious chicken dishes', imageUrl: IMG('chicken-chilli_result.webp'), displayOrder: 2 },
  { name: 'Momos', slug: 'momos', description: 'Steamed & fried dumplings', imageUrl: IMG('chicken-momos_result.webp'), displayOrder: 3 },
  { name: 'Rolls', slug: 'rolls', description: 'Crispy rolls & wraps', imageUrl: IMG('chicken-roll_result.webp'), displayOrder: 4 },
  { name: 'Rice & Noodles', slug: 'rice-noodles', description: 'Fried rice & noodles', imageUrl: IMG('veg-fried-rice_result.webp'), displayOrder: 5 },
  { name: 'Soups', slug: 'soups', description: 'Hot & healthy soups', imageUrl: IMG('chicken-soup_result.webp'), displayOrder: 6 },
  { name: 'Starters', slug: 'starters', description: 'Crispy appetizers', imageUrl: IMG('crispie- fried -chicken_result.webp'), displayOrder: 7 },
  { name: 'Paneer', slug: 'paneer', description: 'Fresh paneer dishes', imageUrl: IMG('paneer-chilli_result.webp'), displayOrder: 8 },
  { name: 'Breads', slug: 'breads', description: 'Indian breads', imageUrl: IMG('lachha-paratha_result.webp'), displayOrder: 9 },
  { name: 'Beverages', slug: 'beverages', description: 'Drinks & water', imageUrl: IMG('mineral-water_result.webp'), displayOrder: 10 },
];

const sliders = [
  {
    title: 'Sizzling Biryani',
    subtitle: 'Chef\'s Special',
    imageUrl: IMG('biryani 1_result.webp'),
    ctaButtonText: 'Order Now',
    linkType: 'category',
    isActive: true,
    displayOrder: 1,
  },
  {
    title: 'Crispy Chicken Lollipop',
    subtitle: 'Best Seller',
    imageUrl: IMG('chicken-lollipop_result.webp'),
    ctaButtonText: 'Try Now',
    linkType: 'category',
    isActive: true,
    displayOrder: 2,
  },
  {
    title: 'Hot Chicken Momos',
    subtitle: 'Steamed Fresh',
    imageUrl: IMG('chicken-momos_result.webp'),
    ctaButtonText: 'Order Now',
    linkType: 'category',
    isActive: true,
    displayOrder: 3,
  },
];

const getProducts = (catMap) => [
  // === BIRYANI ===
  {
    categoryId: catMap['biryani'],
    name: 'Classic Chicken Biryani',
    slug: 'classic-chicken-biryani',
    description: 'Aromatic basmati rice layered with tender chicken, saffron & secret spices. A royal feast in every bite.',
    price: 220,
    discountedPrice: 180,
    imageUrl: IMG('biryani 1_result.webp'),
    imageAlt: 'Classic Chicken Biryani',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: true,
    isFeatured: true,
    spicyLevel: 2,
    tags: ['biryani', 'chicken', 'rice', 'bestseller'],
    servingSize: '1 person',
    prepTimeMinutes: 25,
    averageRating: 4.8,
    totalReviews: 156,
    displayOrder: 1,
  },
  {
    categoryId: catMap['biryani'],
    name: 'Special Biryani',
    slug: 'special-biryani',
    description: 'Our signature biryani with extra tender meat, fried onions & exotic whole spices. A must-try!',
    price: 280,
    discountedPrice: 240,
    imageUrl: IMG('biryani_result.webp'),
    imageAlt: 'Special Biryani',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: true,
    isFeatured: false,
    spicyLevel: 2,
    tags: ['biryani', 'special', 'chicken'],
    servingSize: '1 person',
    prepTimeMinutes: 30,
    averageRating: 4.9,
    totalReviews: 203,
    displayOrder: 2,
  },

  // === CHICKEN ===
  {
    categoryId: catMap['chicken'],
    name: 'Chicken Chilli',
    slug: 'chicken-chilli',
    description: 'Crispy boneless chicken tossed in fiery Indo-Chinese chilli sauce with capsicum & onions.',
    price: 200,
    discountedPrice: 170,
    imageUrl: IMG('chicken-chilli_result.webp'),
    imageAlt: 'Chicken Chilli',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: true,
    isFeatured: true,
    spicyLevel: 3,
    tags: ['chicken', 'chilli', 'starter', 'spicy'],
    servingSize: '2-3 persons',
    prepTimeMinutes: 15,
    averageRating: 4.7,
    totalReviews: 98,
    displayOrder: 1,
  },
  {
    categoryId: catMap['chicken'],
    name: 'Boneless Chicken Chilli',
    slug: 'boneless-chicken-chilli',
    description: 'Tender boneless chicken pieces in rich chilli sauce. Perfectly spiced, perfectly delicious.',
    price: 220,
    discountedPrice: null,
    imageUrl: IMG('boneless-chicken-chillli_result.webp'),
    imageAlt: 'Boneless Chicken Chilli',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 2,
    tags: ['chicken', 'chilli', 'boneless'],
    servingSize: '2-3 persons',
    prepTimeMinutes: 15,
    averageRating: 4.5,
    totalReviews: 67,
    displayOrder: 2,
  },
  {
    categoryId: catMap['chicken'],
    name: 'Chicken Lollipop',
    slug: 'chicken-lollipop',
    description: 'Marinated chicken drumettes fried to perfection. Served with tangy dipping sauce.',
    price: 180,
    discountedPrice: 150,
    imageUrl: IMG('chicken-lollipop_result.webp'),
    imageAlt: 'Chicken Lollipop',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: true,
    isFeatured: true,
    spicyLevel: 2,
    tags: ['chicken', 'lollipop', 'starter', 'bestseller'],
    servingSize: '6 pieces',
    prepTimeMinutes: 20,
    averageRating: 4.8,
    totalReviews: 142,
    displayOrder: 3,
  },
  {
    categoryId: catMap['chicken'],
    name: 'Chicken Leg Piece',
    slug: 'chicken-leg-piece',
    description: 'Juicy marinated chicken leg piece, perfectly grilled. Rich in flavour, irresistibly good.',
    price: 160,
    discountedPrice: null,
    imageUrl: IMG('chicken- leg-piece_result.webp'),
    imageAlt: 'Chicken Leg Piece',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 1,
    tags: ['chicken', 'grilled', 'leg'],
    servingSize: '1 piece',
    prepTimeMinutes: 20,
    averageRating: 4.4,
    totalReviews: 45,
    displayOrder: 4,
  },
  {
    categoryId: catMap['chicken'],
    name: 'Garlic Chicken',
    slug: 'garlic-chicken',
    description: 'Tender chicken cooked with fresh garlic & herbs. Rich, aromatic and absolutely delicious.',
    price: 210,
    discountedPrice: 180,
    imageUrl: IMG('garlic-chicken_result.webp'),
    imageAlt: 'Garlic Chicken',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: true,
    spicyLevel: 1,
    tags: ['chicken', 'garlic', 'special'],
    servingSize: '2 persons',
    prepTimeMinutes: 18,
    averageRating: 4.6,
    totalReviews: 78,
    displayOrder: 5,
  },
  {
    categoryId: catMap['chicken'],
    name: 'Szechuan Chicken',
    slug: 'szechuan-chicken',
    description: 'Bold Szechuan spiced chicken with peppers in a tangy sauce. For the spice lovers!',
    price: 220,
    discountedPrice: 190,
    imageUrl: IMG('sejwan-chicken_result.webp'),
    imageAlt: 'Szechuan Chicken',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 3,
    tags: ['chicken', 'szechuan', 'spicy'],
    servingSize: '2 persons',
    prepTimeMinutes: 15,
    averageRating: 4.5,
    totalReviews: 56,
    displayOrder: 6,
  },
  {
    categoryId: catMap['chicken'],
    name: 'Manchurian',
    slug: 'chicken-manchurian',
    description: 'Classic Indo-Chinese Manchurian in rich gravy. Perfect with fried rice or noodles.',
    price: 190,
    discountedPrice: 160,
    imageUrl: IMG('manchurian_result.webp'),
    imageAlt: 'Chicken Manchurian',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 2,
    tags: ['chicken', 'manchurian', 'gravy'],
    servingSize: '2-3 persons',
    prepTimeMinutes: 15,
    averageRating: 4.5,
    totalReviews: 63,
    displayOrder: 7,
  },
  {
    categoryId: catMap['starters'],
    name: 'Crispy Fried Chicken',
    slug: 'crispy-fried-chicken',
    description: 'Golden crispy fried chicken with secret spice blend. Crunchy outside, juicy inside.',
    price: 200,
    discountedPrice: 170,
    imageUrl: IMG('crispie- fried -chicken_result.webp'),
    imageAlt: 'Crispy Fried Chicken',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: true,
    isFeatured: true,
    spicyLevel: 1,
    tags: ['chicken', 'fried', 'crispy', 'starter'],
    servingSize: '4 pieces',
    prepTimeMinutes: 20,
    averageRating: 4.7,
    totalReviews: 112,
    displayOrder: 1,
  },
  {
    categoryId: catMap['starters'],
    name: 'Chicken Pakoda',
    slug: 'chicken-pakoda',
    description: 'Juicy chicken pieces in crispy gram flour batter. Perfect evening snack with chutney.',
    price: 150,
    discountedPrice: null,
    imageUrl: IMG('chicken-pakoda_result.webp'),
    imageAlt: 'Chicken Pakoda',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 2,
    tags: ['chicken', 'pakoda', 'starter', 'snack'],
    servingSize: '6-8 pieces',
    prepTimeMinutes: 15,
    averageRating: 4.4,
    totalReviews: 54,
    displayOrder: 2,
  },

  // === MOMOS ===
  {
    categoryId: catMap['momos'],
    name: 'Chicken Momos',
    slug: 'chicken-momos',
    description: 'Steamed dumplings filled with spiced minced chicken. Served with red chilli chutney.',
    price: 120,
    discountedPrice: 100,
    imageUrl: IMG('chicken-momos_result.webp'),
    imageAlt: 'Chicken Momos',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: true,
    isFeatured: true,
    spicyLevel: 1,
    tags: ['momos', 'chicken', 'steamed', 'dumpling'],
    servingSize: '8 pieces',
    prepTimeMinutes: 15,
    averageRating: 4.8,
    totalReviews: 189,
    displayOrder: 1,
  },
  {
    categoryId: catMap['momos'],
    name: 'Veg Momos',
    slug: 'veg-momos',
    description: 'Steamed momos stuffed with seasoned vegetables & cheese. Vegetarian delight!',
    price: 100,
    discountedPrice: 85,
    imageUrl: IMG('veg-momos_result.webp'),
    imageAlt: 'Veg Momos',
    isVegetarian: true,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 1,
    tags: ['momos', 'veg', 'steamed', 'dumpling'],
    servingSize: '8 pieces',
    prepTimeMinutes: 12,
    averageRating: 4.5,
    totalReviews: 87,
    displayOrder: 2,
  },

  // === ROLLS ===
  {
    categoryId: catMap['rolls'],
    name: 'Chicken Roll',
    slug: 'chicken-roll',
    description: 'Tender chicken wrapped in paratha with onions, sauce & fresh veggies. Quick & satisfying.',
    price: 100,
    discountedPrice: 85,
    imageUrl: IMG('chicken-roll_result.webp'),
    imageAlt: 'Chicken Roll',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: true,
    isFeatured: true,
    spicyLevel: 1,
    tags: ['roll', 'chicken', 'wrap'],
    servingSize: '1 roll',
    prepTimeMinutes: 10,
    averageRating: 4.6,
    totalReviews: 134,
    displayOrder: 1,
  },
  {
    categoryId: catMap['rolls'],
    name: 'Paneer Roll',
    slug: 'paneer-roll',
    description: 'Spiced paneer tikka wrapped in soft paratha. A vegetarian favourite with tangy chutney.',
    price: 90,
    discountedPrice: 75,
    imageUrl: IMG('paneer-roll_result.webp'),
    imageAlt: 'Paneer Roll',
    isVegetarian: true,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 1,
    tags: ['roll', 'paneer', 'veg', 'wrap'],
    servingSize: '1 roll',
    prepTimeMinutes: 10,
    averageRating: 4.4,
    totalReviews: 67,
    displayOrder: 2,
  },

  // === RICE & NOODLES ===
  {
    categoryId: catMap['rice-noodles'],
    name: 'Chicken Fried Rice',
    slug: 'chicken-fried-rice',
    description: 'Wok-tossed rice with egg, chicken & veggies in classic Indo-Chinese style.',
    price: 150,
    discountedPrice: 130,
    imageUrl: IMG('chicken- fried-rice_result.webp'),
    imageAlt: 'Chicken Fried Rice',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: true,
    spicyLevel: 1,
    tags: ['rice', 'chicken', 'fried rice', 'chinese'],
    servingSize: '1 person',
    prepTimeMinutes: 15,
    averageRating: 4.5,
    totalReviews: 89,
    displayOrder: 1,
  },
  {
    categoryId: catMap['rice-noodles'],
    name: 'Veg Fried Rice',
    slug: 'veg-fried-rice',
    description: 'Flavourful rice tossed with fresh vegetables and soy sauce. Light and delicious.',
    price: 120,
    discountedPrice: 100,
    imageUrl: IMG('veg-fried-rice_result.webp'),
    imageAlt: 'Veg Fried Rice',
    isVegetarian: true,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 0,
    tags: ['rice', 'veg', 'fried rice', 'chinese'],
    servingSize: '1 person',
    prepTimeMinutes: 12,
    averageRating: 4.3,
    totalReviews: 56,
    displayOrder: 2,
  },
  {
    categoryId: catMap['rice-noodles'],
    name: 'Fried Chicken Egg Rice',
    slug: 'fried-chicken-egg-rice',
    description: 'Egg & chicken wok-fried rice with spring onions. Hearty and filling.',
    price: 160,
    discountedPrice: null,
    imageUrl: IMG('fried-chicken-egg-rice_result.webp'),
    imageAlt: 'Fried Chicken Egg Rice',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 1,
    tags: ['rice', 'chicken', 'egg', 'fried rice'],
    servingSize: '1 person',
    prepTimeMinutes: 15,
    averageRating: 4.4,
    totalReviews: 43,
    displayOrder: 3,
  },
  {
    categoryId: catMap['rice-noodles'],
    name: 'Chicken Chowmein',
    slug: 'chicken-chowmein',
    description: 'Wok-tossed noodles with chicken strips & crunchy veggies. Saucy and satisfying.',
    price: 150,
    discountedPrice: 130,
    imageUrl: IMG('chicken-chowmin_result.webp'),
    imageAlt: 'Chicken Chowmein',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 1,
    tags: ['noodles', 'chicken', 'chowmein', 'chinese'],
    servingSize: '1 person',
    prepTimeMinutes: 12,
    averageRating: 4.5,
    totalReviews: 78,
    displayOrder: 4,
  },
  {
    categoryId: catMap['rice-noodles'],
    name: 'Veg Chowmein',
    slug: 'veg-chowmein',
    description: 'Classic veg noodles tossed with colourful vegetables and sauces. Light and tasty.',
    price: 120,
    discountedPrice: null,
    imageUrl: IMG('veg-chowmin_result.webp'),
    imageAlt: 'Veg Chowmein',
    isVegetarian: true,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 1,
    tags: ['noodles', 'veg', 'chowmein', 'chinese'],
    servingSize: '1 person',
    prepTimeMinutes: 12,
    averageRating: 4.3,
    totalReviews: 45,
    displayOrder: 5,
  },
  {
    categoryId: catMap['rice-noodles'],
    name: 'Paneer Chowmein',
    slug: 'paneer-chowmein',
    description: 'Soft paneer cubes tossed in noodles with herbs. A vegetarian noodle treat.',
    price: 140,
    discountedPrice: 120,
    imageUrl: IMG('paneer-chowmin_result.webp'),
    imageAlt: 'Paneer Chowmein',
    isVegetarian: true,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 1,
    tags: ['noodles', 'paneer', 'chowmein'],
    servingSize: '1 person',
    prepTimeMinutes: 12,
    averageRating: 4.4,
    totalReviews: 34,
    displayOrder: 6,
  },

  // === SOUPS ===
  {
    categoryId: catMap['soups'],
    name: 'Chicken Soup',
    slug: 'chicken-soup',
    description: 'Warm comforting chicken broth with vegetables and herbs. Perfect for any season.',
    price: 100,
    discountedPrice: 85,
    imageUrl: IMG('chicken-soup_result.webp'),
    imageAlt: 'Chicken Soup',
    isVegetarian: false,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 0,
    tags: ['soup', 'chicken', 'healthy'],
    servingSize: '1 bowl',
    prepTimeMinutes: 10,
    averageRating: 4.4,
    totalReviews: 45,
    displayOrder: 1,
  },
  {
    categoryId: catMap['soups'],
    name: 'Vegetable Soup',
    slug: 'vegetable-soup',
    description: 'Light and nourishing vegetable soup with fresh garden produce. Healthy & delicious.',
    price: 80,
    discountedPrice: null,
    imageUrl: IMG('vegetable-soup_result.webp'),
    imageAlt: 'Vegetable Soup',
    isVegetarian: true,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 0,
    tags: ['soup', 'veg', 'healthy'],
    servingSize: '1 bowl',
    prepTimeMinutes: 8,
    averageRating: 4.2,
    totalReviews: 32,
    displayOrder: 2,
  },

  // === PANEER ===
  {
    categoryId: catMap['paneer'],
    name: 'Paneer Chilli',
    slug: 'paneer-chilli',
    description: 'Crispy paneer cubes tossed in spicy Indo-Chinese chilli sauce. Vegetarian delight.',
    price: 180,
    discountedPrice: 150,
    imageUrl: IMG('paneer-chilli_result.webp'),
    imageAlt: 'Paneer Chilli',
    isVegetarian: true,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: true,
    spicyLevel: 2,
    tags: ['paneer', 'chilli', 'veg', 'starter'],
    servingSize: '2-3 persons',
    prepTimeMinutes: 15,
    averageRating: 4.6,
    totalReviews: 76,
    displayOrder: 1,
  },
  {
    categoryId: catMap['paneer'],
    name: 'Paneer Masala',
    slug: 'paneer-masala',
    description: 'Rich and creamy paneer in aromatic tomato-based masala gravy. Best with naan.',
    price: 200,
    discountedPrice: 170,
    imageUrl: IMG('paneer-masala_result.webp'),
    imageAlt: 'Paneer Masala',
    isVegetarian: true,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 1,
    tags: ['paneer', 'masala', 'gravy', 'veg'],
    servingSize: '2-3 persons',
    prepTimeMinutes: 18,
    averageRating: 4.5,
    totalReviews: 58,
    displayOrder: 2,
  },

  // === BREADS ===
  {
    categoryId: catMap['breads'],
    name: 'Lachha Paratha',
    slug: 'lachha-paratha',
    description: 'Flaky layered whole wheat paratha. Perfectly crispy on outside, soft inside.',
    price: 40,
    discountedPrice: null,
    imageUrl: IMG('lachha-paratha_result.webp'),
    imageAlt: 'Lachha Paratha',
    isVegetarian: true,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 0,
    tags: ['bread', 'paratha', 'veg'],
    servingSize: '2 parathas',
    prepTimeMinutes: 10,
    averageRating: 4.5,
    totalReviews: 67,
    displayOrder: 1,
  },

  // === BEVERAGES ===
  {
    categoryId: catMap['beverages'],
    name: 'Mineral Water',
    slug: 'mineral-water',
    description: 'Chilled mineral water. Stay hydrated with your meal.',
    price: 20,
    discountedPrice: null,
    imageUrl: IMG('mineral-water_result.webp'),
    imageAlt: 'Mineral Water',
    isVegetarian: true,
    isAvailable: true,
    isBestSeller: false,
    isFeatured: false,
    spicyLevel: 0,
    tags: ['water', 'beverage', 'drink'],
    servingSize: '1 bottle (500ml)',
    prepTimeMinutes: 0,
    averageRating: 5.0,
    totalReviews: 120,
    displayOrder: 1,
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    await Category.deleteMany({});
    await Product.deleteMany({});
    await Slider.deleteMany({});
    console.log('🗑️  Cleared existing data');

    // Insert categories
    const insertedCats = await Category.insertMany(categories);
    console.log(`✅ Inserted ${insertedCats.length} categories`);

    // Build slug -> _id map
    const catMap = {};
    insertedCats.forEach(c => { catMap[c.slug] = c._id; });

    // Insert products
    const products = getProducts(catMap);
    const insertedProds = await Product.insertMany(products);
    console.log(`✅ Inserted ${insertedProds.length} products`);

    // Insert sliders
    const insertedSliders = await Slider.insertMany(sliders);
    console.log(`✅ Inserted ${insertedSliders.length} sliders`);

    // Upsert settings
    await Settings.findOneAndUpdate(
      {},
      {
        restaurantName: 'Laziz Restaurant',
        whatsappNumber: '917667941496',
        address: 'Jainagar, Patna, Bihar — 801109',
        phone: '+91 76679 41496',
        email: 'laziz@restaurant.com',
        isOpen: true,
        operatingHours: [
          'Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'
        ].map(day => ({ day, isOpen: true, openTime: '11:00', closeTime: '23:00' })),
      },
      { upsert: true, new: true }
    );
    console.log('✅ Settings saved');

    console.log('\n🎉 SEEDING COMPLETE!\n');
    console.log('Categories:', insertedCats.map(c => c.name).join(', '));
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
    process.exit(1);
  }
}

seed();
